DROP DATABASE IF EXISTS CGV;

CREATE DATABASE CGV;

USE CGV;

DROP TABLE IF EXISTS `MOVIE`;

CREATE TABLE `MOVIE` (
	`MO_NUM`	INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`MO_TITLE`	VARCHAR(50) NOT NULL,
	`MO_TITLE_ENG`	VARCHAR(100) NOT NULL,
	`MO_OPENING_DATE`	DATE NULL,
	`MO_RUNNING_TIME`	INT	NOT NULL,
	`MO_PLOT`	LONGTEXT NOT NULL,
	`MO_FI_NUM`	INT	NOT NULL,
	`MO_AG_NAME`	VARCHAR(10)	NOT NULL,
	`MO_RESERVATION_RATE`	INT	NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS `GENRE`;

CREATE TABLE `GENRE` (
	`GE_NAME`	VARCHAR(10)	NOT NULL PRIMARY KEY
);

DROP TABLE IF EXISTS `MOVIE_GENRE`;

CREATE TABLE `MOVIE_GENRE` (
	`MG_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`MG_GE_NAME`	VARCHAR(10)	NOT NULL,
	`MG_MO_NUM`	INT NOT NULL
);

DROP TABLE IF EXISTS `COUNTRY`;

CREATE TABLE `COUNTRY` (
	`CT_NAME`	VARCHAR(20)	NOT NULL PRIMARY KEY
);

DROP TABLE IF EXISTS `COUNTRY_PRODUCTION`;

CREATE TABLE `COUNTRY_PRODUCTION` (
	`CP_NUM`	INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`CP_CT_NAME`	VARCHAR(20)	NOT NULL,
	`CP_MO_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `FILM_PERSON`;

CREATE TABLE `FILM_PERSON` (
	`FP_NUM`	INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`FP_NAME`	VARCHAR(20)	NOT NULL,
	`FP_THUMB`	VARCHAR(50)	NULL,
	`FP_AGENCY`	VARCHAR(20)	NULL,
	`FP_FINAL_EDUCATION`	VARCHAR(20)	NULL,
	`FP_BIRTHDAY`	DATE NOT NULL,
	`FP_CT_NAME`	VARCHAR(20)	NOT NULL
);

DROP TABLE IF EXISTS `ROLE`;

CREATE TABLE `ROLE` (
	`RO_NUM`	INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`RO_ROLE`	VARCHAR(30)	NOT NULL,
	`RO_FP_NUM`	INT	NOT NULL,
	`RO_MO_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `FILE`;

CREATE TABLE `FILE` (
	`FI_NUM`	INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`FI_NAME`	VARCHAR(100)	NOT NULL,
	`FI_STATE`	VARCHAR(10)	NOT NULL -- 메인포스트 / 트레일러 / 스틸컷
);

DROP TABLE IF EXISTS `MOVIE_FILE`;

CREATE TABLE `MOVIE_FILE` (
	`MF_NUM`	INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`MF_FI_NUM`	INT	NOT NULL,
	`MF_MO_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `AGE`;

CREATE TABLE `AGE` (
	`AG_NAME`	VARCHAR(10)	NOT NULL PRIMARY KEY
);

DROP TABLE IF EXISTS `THEATER`;

CREATE TABLE `THEATER` (
	`TH_NUM`	INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`TH_NAME`	VARCHAR(20)	NOT NULL,
	`TH_ADDRESS`	VARCHAR(50) NOT	NULL,
	`TH_RE_NAME`	VARCHAR(15)	NOT NULL,
	`TH_TOTAL_SCREEN`	INT	NOT NULL DEFAULT 1,
	`TH_TOTAL_SEAT`	INT	NOT NULL
);

DROP TABLE IF EXISTS `REGION`;

CREATE TABLE `REGION` (
	`RE_NAME`	VARCHAR(15)	NOT NULL PRIMARY KEY
);

DROP TABLE IF EXISTS `SCREEN`;

CREATE TABLE `SCREEN` (
	`SC_NUM`	INT	NOT NULL,
	`SC_NAME`	VARCHAR(20)	NULL,
	`SC_TOTAL_SEAT`	INT	NULL,
	`SC_TH_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `SEAT`;

CREATE TABLE `SEAT` (
	`SE_NUM`	INT	NOT NULL,
	`SE_NAME`	VARCHAR(4)	NULL,
	`SE_ROW`	CHAR(1)	NULL,
	`SE_COL`	VARCHAR(2)	NULL,
	`SE_STATE`	VARCHAR(10)	NULL,
	`SE_SC_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `MOVIE_SCHEDULE`;

CREATE TABLE `MOVIE_SCHEDULE` (
	`MS_NUM`	INT	NOT NULL,
	`MS_MO_NUM`	INT	NOT NULL,
	`MS_SC_NUM`	INT	NOT NULL,
	`MS_DATE`	DATE	NULL,
	`MS_START_TIME`	TIME	NULL,
	`MS_END_TIME`	TIME	NULL,
	`MS_POSSIBLE_SEAT`	INT	NULL,
	`MS_DISCOUNT`	CHAR(1)	NULL
);

DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `MEMBER` (
	`ME_ID`	VARCHAR(15)	NOT NULL,
	`ME_PW`	VARCHAR(20)	NULL,
	`ME_NAME`	VARCHAR(20)	NULL,
	`ME_PHONE`	VARCHAR(20)	NULL,
	`ME_BIRTHDAY`	DATE	NULL
);

DROP TABLE IF EXISTS `RESERVATION`;

CREATE TABLE `RESERVATION` (
	`RV_NUM`	VARCHAR(30)	NOT NULL,
	`RV_ADULT`	INT	NULL,
	`RV_TEENAGER`	INT	NULL,
	`RV_PRICE`	INT	NULL,
	`RV_ME_ID`	VARCHAR(15)	NOT NULL,
	`RV_MS_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `RESERVATION_LIST`;

CREATE TABLE `RESERVATION_LIST` (
	`RL_NUM`	INT	NOT NULL,
	`RL_RV_NUM`	VARCHAR(30)	NOT NULL,
	`RL_SE_NUM`	INT	NOT NULL,
	`RL_PR_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `PRICE`;

CREATE TABLE `PRICE` (
	`PR_NUM`	INT	NOT NULL,
	`PR_TYPE`	VARCHAR(3)	NULL,
	`PR_PRICE`	INT	NULL,
	`PR_DISCOUNT_PRICE`	INT	NULL
);

DROP TABLE IF EXISTS `REVIEW`;

CREATE TABLE `REVIEW` (
	`RE_NUM`	INT	NOT NULL,
	`RE_CONTENT`	LONGTEXT	NULL,
	`RE_MO_NUM`	INT	NOT NULL,
	`RE_ME_ID`	VARCHAR(15)	NOT NULL,
	`RE_TOTAL_LIKE`	INT	NULL
);

DROP TABLE IF EXISTS `LIKE`;

CREATE TABLE `LIKE` (
	`LI_NUM`	INT	NOT NULL,
	`LI_ME_ID`	VARCHAR(15)	NOT NULL,
	`LI_RE_NUM`	INT	NOT NULL
);

ALTER TABLE `MOVIE` ADD CONSTRAINT `PK_MOVIE` PRIMARY KEY (
	`MO_NUM`
);

ALTER TABLE `GENRE` ADD CONSTRAINT `PK_GENRE` PRIMARY KEY (
	`GE_NAME`
);

ALTER TABLE `MOVIE_GENRE` ADD CONSTRAINT `PK_MOVIE_GENRE` PRIMARY KEY (
	`MG_NUM`
);

ALTER TABLE `COUNTRY` ADD CONSTRAINT `PK_COUNTRY` PRIMARY KEY (
	`CT_NAME`
);

ALTER TABLE `COUNTRY_PRODUCTION` ADD CONSTRAINT `PK_COUNTRY_PRODUCTION` PRIMARY KEY (
	`CP_NUM`
);

ALTER TABLE `FILM_PERSON` ADD CONSTRAINT `PK_FILM_PERSON` PRIMARY KEY (
	`FP_NUM`
);

ALTER TABLE `ROLE` ADD CONSTRAINT `PK_ROLE` PRIMARY KEY (
	`RO_NUM`
);

ALTER TABLE `FILE` ADD CONSTRAINT `PK_FILE` PRIMARY KEY (
	`FI_NUM`
);

ALTER TABLE `MOVIE_FILE` ADD CONSTRAINT `PK_MOVIE_FILE` PRIMARY KEY (
	`MF_NUM`
);

ALTER TABLE `AGE` ADD CONSTRAINT `PK_AGE` PRIMARY KEY (
	`AG_NAME`
);

ALTER TABLE `THEATER` ADD CONSTRAINT `PK_THEATER` PRIMARY KEY (
	`TH_NUM`
);

ALTER TABLE `REGION` ADD CONSTRAINT `PK_REGION` PRIMARY KEY (
	`RE_NAME`
);

ALTER TABLE `SCREEN` ADD CONSTRAINT `PK_SCREEN` PRIMARY KEY (
	`SC_NUM`
);

ALTER TABLE `SEAT` ADD CONSTRAINT `PK_SEAT` PRIMARY KEY (
	`SE_NUM`
);

ALTER TABLE `MOVIE_SCHEDULE` ADD CONSTRAINT `PK_MOVIE_SCHEDULE` PRIMARY KEY (
	`MS_NUM`
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`ME_ID`
);

ALTER TABLE `RESERVATION` ADD CONSTRAINT `PK_RESERVATION` PRIMARY KEY (
	`RV_NUM`
);

ALTER TABLE `RESERVATION_LIST` ADD CONSTRAINT `PK_RESERVATION_LIST` PRIMARY KEY (
	`RL_NUM`
);

ALTER TABLE `PRICE` ADD CONSTRAINT `PK_PRICE` PRIMARY KEY (
	`PR_NUM`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `PK_REVIEW` PRIMARY KEY (
	`RE_NUM`
);

ALTER TABLE `LIKE` ADD CONSTRAINT `PK_LIKE` PRIMARY KEY (
	`LI_NUM`
);

ALTER TABLE `MOVIE` ADD CONSTRAINT `FK_FILE_TO_MOVIE_1` FOREIGN KEY (
	`MO_FI_NUM`
)
REFERENCES `FILE` (
	`FI_NUM`
);

ALTER TABLE `MOVIE` ADD CONSTRAINT `FK_AGE_TO_MOVIE_1` FOREIGN KEY (
	`MO_AG_NAME`
)
REFERENCES `AGE` (
	`AG_NAME`
);

ALTER TABLE `MOVIE_GENRE` ADD CONSTRAINT `FK_GENRE_TO_MOVIE_GENRE_1` FOREIGN KEY (
	`MG_GE_NAME`
)
REFERENCES `GENRE` (
	`GE_NAME`
);

ALTER TABLE `MOVIE_GENRE` ADD CONSTRAINT `FK_MOVIE_TO_MOVIE_GENRE_1` FOREIGN KEY (
	`MG_MO_NUM`
)
REFERENCES `MOVIE` (
	`MO_NUM`
);

ALTER TABLE `COUNTRY_PRODUCTION` ADD CONSTRAINT `FK_COUNTRY_TO_COUNTRY_PRODUCTION_1` FOREIGN KEY (
	`CP_CT_NAME`
)
REFERENCES `COUNTRY` (
	`CT_NAME`
);

ALTER TABLE `COUNTRY_PRODUCTION` ADD CONSTRAINT `FK_MOVIE_TO_COUNTRY_PRODUCTION_1` FOREIGN KEY (
	`CP_MO_NUM`
)
REFERENCES `MOVIE` (
	`MO_NUM`
);

ALTER TABLE `FILM_PERSON` ADD CONSTRAINT `FK_COUNTRY_TO_FILM_PERSON_1` FOREIGN KEY (
	`FP_CT_NAME`
)
REFERENCES `COUNTRY` (
	`CT_NAME`
);

ALTER TABLE `ROLE` ADD CONSTRAINT `FK_FILM_PERSON_TO_ROLE_1` FOREIGN KEY (
	`RO_FP_NUM`
)
REFERENCES `FILM_PERSON` (
	`FP_NUM`
);

ALTER TABLE `ROLE` ADD CONSTRAINT `FK_MOVIE_TO_ROLE_1` FOREIGN KEY (
	`RO_MO_NUM`
)
REFERENCES `MOVIE` (
	`MO_NUM`
);

ALTER TABLE `MOVIE_FILE` ADD CONSTRAINT `FK_FILE_TO_MOVIE_FILE_1` FOREIGN KEY (
	`MF_FI_NUM`
)
REFERENCES `FILE` (
	`FI_NUM`
);

ALTER TABLE `MOVIE_FILE` ADD CONSTRAINT `FK_MOVIE_TO_MOVIE_FILE_1` FOREIGN KEY (
	`MF_MO_NUM`
)
REFERENCES `MOVIE` (
	`MO_NUM`
);

ALTER TABLE `THEATER` ADD CONSTRAINT `FK_REGION_TO_THEATER_1` FOREIGN KEY (
	`TH_RE_NAME`
)
REFERENCES `REGION` (
	`RE_NAME`
);

ALTER TABLE `SCREEN` ADD CONSTRAINT `FK_THEATER_TO_SCREEN_1` FOREIGN KEY (
	`SC_TH_NUM`
)
REFERENCES `THEATER` (
	`TH_NUM`
);

ALTER TABLE `SEAT` ADD CONSTRAINT `FK_SCREEN_TO_SEAT_1` FOREIGN KEY (
	`SE_SC_NUM`
)
REFERENCES `SCREEN` (
	`SC_NUM`
);

ALTER TABLE `MOVIE_SCHEDULE` ADD CONSTRAINT `FK_MOVIE_TO_MOVIE_SCHEDULE_1` FOREIGN KEY (
	`MS_MO_NUM`
)
REFERENCES `MOVIE` (
	`MO_NUM`
);

ALTER TABLE `MOVIE_SCHEDULE` ADD CONSTRAINT `FK_SCREEN_TO_MOVIE_SCHEDULE_1` FOREIGN KEY (
	`MS_SC_NUM`
)
REFERENCES `SCREEN` (
	`SC_NUM`
);

ALTER TABLE `RESERVATION` ADD CONSTRAINT `FK_MEMBER_TO_RESERVATION_1` FOREIGN KEY (
	`RV_ME_ID`
)
REFERENCES `MEMBER` (
	`ME_ID`
);

ALTER TABLE `RESERVATION` ADD CONSTRAINT `FK_MOVIE_SCHEDULE_TO_RESERVATION_1` FOREIGN KEY (
	`RV_MS_NUM`
)
REFERENCES `MOVIE_SCHEDULE` (
	`MS_NUM`
);

ALTER TABLE `RESERVATION_LIST` ADD CONSTRAINT `FK_RESERVATION_TO_RESERVATION_LIST_1` FOREIGN KEY (
	`RL_RV_NUM`
)
REFERENCES `RESERVATION` (
	`RV_NUM`
);

ALTER TABLE `RESERVATION_LIST` ADD CONSTRAINT `FK_SEAT_TO_RESERVATION_LIST_1` FOREIGN KEY (
	`RL_SE_NUM`
)
REFERENCES `SEAT` (
	`SE_NUM`
);

ALTER TABLE `RESERVATION_LIST` ADD CONSTRAINT `FK_PRICE_TO_RESERVATION_LIST_1` FOREIGN KEY (
	`RL_PR_NUM`
)
REFERENCES `PRICE` (
	`PR_NUM`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_MOVIE_TO_REVIEW_1` FOREIGN KEY (
	`RE_MO_NUM`
)
REFERENCES `MOVIE` (
	`MO_NUM`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_MEMBER_TO_REVIEW_1` FOREIGN KEY (
	`RE_ME_ID`
)
REFERENCES `MEMBER` (
	`ME_ID`
);

ALTER TABLE `LIKE` ADD CONSTRAINT `FK_MEMBER_TO_LIKE_1` FOREIGN KEY (
	`LI_ME_ID`
)
REFERENCES `MEMBER` (
	`ME_ID`
);

ALTER TABLE `LIKE` ADD CONSTRAINT `FK_REVIEW_TO_LIKE_1` FOREIGN KEY (
	`LI_RE_NUM`
)
REFERENCES `REVIEW` (
	`RE_NUM`
);

